packages:
  - 'src/leafer'
  - 'src/leafer/packages/*'
  - 'src/leafer/packages/core/*'
  - 'src/leafer/packages/platform/*'
  - 'src/leafer/packages/display-module/*'
  - 'src/leafer/packages/canvas/*'
  - 'src/leafer/packages/image/*'
  - 'src/leafer/packages/partner/*'
  - 'src/ui'
  - 'src/ui/packages/*'
  - 'src/ui/packages/core/*'
  - 'src/ui/packages/platform/*'
  - 'src/ui/packages/display-module/*'
  - 'src/ui/packages/interaction/*'
  - 'src/ui/packages/partner/*'
  - 'src/in'
  - 'src/in/packages/*'
  - 'src/draw'
  - 'src/draw/packages/*'
  - 'src/draw/packages/platform/*'
  - 'src/editor'
  - 'src/editor/packages/*'
  - 'src/editor/packages/platform/*'
  - 'src/game'
  - 'src/game/packages/*'
  - 'src/game/packages/platform/*'
